### ISSUE TITLE
My suggestions!

### ISSUE THREAD

**Issue by schwungvoll** [Smug246/Luna-Token-Grabber#45] opened 2022-10-21 14:09 UTC
**Here are a few suggestions. Yes I know, some of that is ransomware/malware or a remote control program but it would make the grabber just more interesting and useful.**

- an option in the builder that you can enable Webcam Screenshot (yes it makes the file really big but yeah for people that say things like `"yup thats my own game can you try it?"` that would be just nice)
- `add a custom icon` feature (just have to drag and drop .png/.jpeg/.ico file)
- remove line 127 for everyone (the bug that prevents users from opening and building the file, so in general more bug fixes)
- a new and own, clean GUI for the builder like `Blitzed and Blank Grabber` have
- auto-update feature (if a new version of the grabber is out the new version will be automatically installed on the infected pc, would be awesome if this was possible)
- pretty small RAT feature in it or as a new project (Start/Stop Keylogger, Delete itself, make a weird noise, so generally just some small commands, if in luna, option to disable or enable it)
- Anti-VM and Anti-Sandbox (I don't really know if this is already there)
- an option to choose what user data you need or want
like this:
`Passwords, Bookmarks, Cookies? (y/N)
System Info? (y/N)
Token and other information about Discord? (y/N)`
- a binder as an extra option that you can directly bind it after built with other files

**Comment by Smug246** [comment] 2022-10-21 14:48
webcam option - yes
custom icon - yes
line 127 - not a bug people just got shit computers
custom gui - i like the terminal look more than an actual gui. i dont rate tkinter.
auto-update - impossible, wouldnt make sense or be practical.
rat feature - not adding any rat features. i would've have done these already.
anti-vm and sandbox already added
option for data - nah they can find a less good grabber if they want less stuff. more options makes it just look clunky
binder - yes in the future. already on my to do list

**Comment by schwungvoll** [comment] 2022-10-21 14:50
May I ask why you don't like these RAT features?

**Comment by Smug246** [comment] 2022-10-21 14:51
i want to purely keep it as a logger. if i wanted rat features i could make a rat

**Comment by schwungvoll** [comment] 2022-10-21 14:53
And what's about auto-update? So it not possible or don't you just like it? e.g. the file gets detected by Windows Defender for everyone and there is a new version that supports more browsers and is more undectect. It would be useful in such a situation.

**Comment by Smug246** [comment] 2022-10-21 15:01
ill explain to you why it wouldn't work. lets say you build the file with obfuscation and compile it to a .exe. it wouldnt be possible to dekrypt the .exe and obfuscation. rewrite whatever said changes ive made then obfuscate it back and then also compile it again. thats on someone elses computer too. just woudlnt be able to work.

**Comment by SlepPoweredBy2** [comment] 2022-10-22 06:13
nigga how about u make us a rat

**Comment by schwungvoll** [comment] 2022-10-22 09:42
> nigga how about u make us a rat

1. You're the only nigger here
2. make your own, fucking shitty ass kid

**Comment by Smug246** [comment] 2022-10-22 09:54
lmao

**Comment by SlepPoweredBy2** [comment] 2022-10-22 09:59
> > nigga how about u make us a rat
> 
> 1. You're the only nigger here
> 2. make your own, fucking shitty ass kid

shut the fuck up ur probably 9 and u think ur cheataway lmfao i could beat ur ass a 1000 times little shit

**Comment by schwungvoll** [comment] 2022-10-22 10:08
> > > nigga how about u make us a rat
> > 
> > 1. You're the only nigger here
> > 2. make your own, fucking shitty ass kid
> 
> shut the fuck up ur probably 9 and u think ur cheataway lmfao i could beat ur ass a 1000 times little shit

lmao stfu just code your own shit and don't beg you lil ass kid with 2 dads 💀💀

**Comment by Smug246** [comment] 2022-10-22 10:09
> nigga how about u make us a rat

if you want a rat just search rat. there's loads already

**Comment by schwungvoll** [comment] 2022-10-22 10:09
> > > nigga how about u make us a rat
> > 
> > 1. You're the only nigger here
> > 2. make your own, fucking shitty ass kid
> 
> shut the fuck up ur probably 9 and u think ur cheataway lmfao i could beat ur ass a 1000 times little shit

the only thing you could beat is your mom but I already did

**Comment by SlepPoweredBy2** [comment] 2022-10-22 10:09
> > nigga how about u make us a rat
> 
> if you want a rat just search rat. there's loads already

godgenesis is a good one

**Comment by SlepPoweredBy2** [comment] 2022-10-22 13:09
> > > > nigga how about u make us a rat
> > > 
> > > 
> > > 
> > > 1. You're the only nigger here
> > > 2. make your own, fucking shitty ass kid
> > 
> > 
> > shut the fuck up ur probably 9 and u think ur cheataway lmfao i could beat ur ass a 1000 times little shit
> 
> the only thing you could beat is your mom but I already did

no way u just said that 😭 😭 
typical 9 year old kid

**Comment by schwungvoll** [comment] 2022-10-23 10:08
typical nigger with no life feeling like the main character on github stfu you just get no love from ur parents

**Comment by Smug246** [comment] 2022-10-23 13:24
i added all these to the do list so gonna close the issue now

**Closed by Smug246** 2022-10-23 13:24 UTC
Labels: documentation, enhancement
